version: "3.9"
services:
  app:
    build: .
    image: proxy-forwarder:latest
    # Load defaults from local .env (git-ignored). Explicit env below override it for container usage.
    env_file:
      - .env
    environment:
      - BIND_ADDR=0.0.0.0:8080
      - REDIS_URL=redis://redis:6379
      - FORWARD_TIMEOUT_MS=5000
      - CACHE_TTL_SECS=60
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
